name: AidensPlugin
version: 1.0
author: Atomic Pixels
main: aidensplugin.Main
api-version: 1.16

commands:
  heal:
    description: Heals the player fully
    usage: /heal [player]
    permission: aidensplugin.heal
    permission-message: You do not have permission to use that command.
  feed:
    description: Feeds the player fully
    usage: /feed [player]
    permission: aidensplugin.feed
    permission-message: You do not have permission to use that command.
  give-thunderstick:
    description: Gives designated player the Thunder Stick
    usage: /give-thunderstick [player]
    aliases: [give-ts]
    permission: aidensplugin.give-ts
    permission-message: You do not have permission to use that command.
  give-mechanicalboots:
    description: Gives designated player Mechanical Boots
    usage: /give-mechanicalboots [player]
    aliases: [give-mb]
    permission: aidensplugin.give-mb
    permission-message: You do not have permission to use that command.
  give-enderbow:
    description: Gives designated player Ender Bow
    usage: /give-enderbow [player]
    aliases: [ give-eb ]
    permission: aidensplugin.give-eb
    permission-message: You do not have permission to use that command.
  give-flynnstick:
    description: Gives designated player the Flynn Stick
    usage: /give-flynnstick [player]
    aliases: [ give-fs ]
    permission: aidensplugin.give-fs
    permission-message: You do not have permission to use that command.
  give-enchantedgem:
    description: Gives designated player an Enchanted Gem
    usage: /give-enchantedgem [player] <amount>
    aliases: [ give-eg ]
    permission: aidensplugin.give-eg
    permission-message: You do not have permission to use that command.
  give-minersgem:
    description: Gives designated player a Miners Gem
    usage: /give-minersgem [player] <amount>
    aliases: [ give-mg ]
    permission: aidensplugin.give-mg
    permission-message: You do not have permission to use that command.
  give-infinitehotsnowball:
    description: Gives designated player a Infinite Hot Snowball
    usage: /give-infinitehotsnowball [player] <amount>
    aliases: [ give-ihs ]
    permission: aidensplugin.give-ihs
    permission-message: You do not have permission to use that command.
  give-cavingflower:
    description: Gives designated player caving Flower
    usage: /give-cavingflower [player] <amount>
    aliases: [ give-cf ]
    permission: aidensplugin.give-cf
    permission-message: You do not have permission to use that command.
  give-fishhelm:
    description: Gives designated player Fish Helm
    usage: /give-fishhelm [player] <amount>
    aliases: [ give-fh ]
    permission: aidensplugin.give-fh
    permission-message: You do not have permission to use that command.
  craft:
    description: Craft designated item in specified amount
    usage: /craft <item> <amount>
    aliases: [ cft ]
    permission: aidensplugin.craft
    permission-message: You do not have permission to use that command.
  extract:
    description: Skill that allows you to extract enchanted books from an item.
    usage: /extract
    aliases: [ ee ]
    permission: aidensplugin.extract
    permission-message: You do not have permission to use that command.